### ISSUE TITLE
Slugs deletion

### ISSUE THREAD

**Issue by vinzvinci** [DenverCoder1/custom-icon-badges#103]
Is it possible if we submit a request to delete **Slug** (name of the logo)?

**Comment by DenverCoder1** [comment]
I can delete them through the mongo db UI if you tell me what you want removed.

Alternatively, you can choose a different slug that is slightly different from the first if there's a problem with the first one.

I can't easily add deleting slugs as a website feature unless accounts and stuff like that are added since I wouldn't want people deleting other people's slugs.

**Comment by vinzvinci** [comment]
I see. Hmm okay, please delete these: 
- devprotocol
- dev-protocol
- devprtcl

xD. That's all ^^ Thank you

**Comment by DenverCoder1** [comment]
I have removed them. Feel free to let me know if you have any more questions :+1:

**Comment by WorldOfDex** [comment]
Please Remove the TallyPrime Too
